version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: my-BDapi
    restart: always

    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_BD}

    volumes:
      - ./postgres:/var/lib/postgresql/data
